### ISSUE TITLE
allow specifying different tls backend for reqwest

### ISSUE THREAD

**Issue by sify21** [mibes/couch-rs#10]
`reqwest` uses `native-tls` by default, which requires openssl in os. for example,  [this project](https://replit.com/@sify21/couchrs) won't build on replit.

**Comment by mibes** [comment]
Do you have an idea how to do this? Or a sample project that has implemented this behaviour?

**Comment by sify21** [comment]
I used to do this using features,  I made a sample pull request for this

**Comment by mibes** [comment]
Included in 0.8.32 release. Thanks for your contribution!
