### ISSUE TITLE
Client.exists method returns true without existing database

### ISSUE THREAD

**Issue by wrazik** [mibes/couch-rs#15]
Hi!

Thank you for great job with this crate! It's really helpful & I'm intensively using it in the production.

I've observed that method exists returns true even if database does not exists.

I'm attaching the screenshot from the debugger. As you see - somewhere deep inside http::status::StatusCode is `404`, but method returns `true`.
![debug_failing_exists](https://user-images.githubusercontent.com/6102580/141352658-96a01d46-363d-43be-b23e-edbebbfe59f9.png)

**Comment by mibes** [comment]
Thanks for pointing this out!

This issue has been fixed in the `0.8.33` release.

**Comment by wrazik** [comment]
I'm really impressed with reaction time. 

I've tested the correction & everything works well! Love it!
