### ISSUE TITLE
Upgrade to rust 2021 causing compatibility issues. 

### ISSUE THREAD

**Issue by kingledion** [mibes/couch-rs#17]
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/couch_rs-0.8.33/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature

This is causing a big problem for me because I'm trying to stay on rust 1.53 due to some other linker problem. I can't build new versions of my webserver now, until I can figure out how to upgrade to 1.56 and edition 2021.

It seems like any include of couch_rs 0.8.32 is still pulling the 0.8.33 version. 

I wish you would have made this last release version 0.9 to make this upgrade easy for me.

**Comment by mibes** [comment]
Hi Daniel,

Thanks for bringing this up. 

I've just released `v0.8.34` in which we reverted the edition to `2018`. We're not using anything of the `2021` edition at the moment, so we'll keep it like this for now. 

If we need/want to move to the `2021` edition, we'll follow your suggestion to create a `0.9` release to ensure backwards compatibility for as long as possible.

**Comment by kingledion** [comment]
I want to thank you for this. Appreciate the quick action.
