### ISSUE TITLE
Description of `database::Database::insert_index` is not accurate

### ISSUE THREAD

**Issue by kingledion** [mibes/couch-rs#26]
The docs for [insert_index](https://docs.rs/couch_rs/latest/couch_rs/database/struct.Database.html#method.insert_index) says:
> Inserts an index in a naive way, if it already exists, will throw an Err

This is not accurate. When an index already exists, the `DesignCreated::results` field will be "exists" and no error will be thrown. Because of this behavior, the `ensure_index` method on `Database` doesn't really have any purpose. 

In my mind, the primary purpose of a method like `ensure_index` is to run in a 'migration' job before an application depending on couch_rs is launched. A method like this would ensure that the database in question has the indexes that are expected by the application code.

I propose the following changes:
 - Update the docs for `insert_index` to reflect its actual behavior.
 - Add a doctest that will validate this behavior
 - Update the arguments to `insert_index` to match the `types::index::Index` struct, to make it more compatible with the `get_indexes` method. 
 - Create an enum for the `IndexType` as defined in the CouchDB docs
 - Make a new `ensure_index` function that will take a vector of Index and either validate that they exist in the database or create them.

**Comment by kingledion** [comment]
I can't appear to link this in Development, but this is the working branch of changes: https://github.com/kingledion/couch-rs/tree/improve-indexing

As of this post, I'm about 50% done with creating tests. There is a doctest for insert_index, but I'd like to also add a test for ensure_index (not sure if doctest or unit test yet...I'm currently testing this function in another application, locally).

**Comment by horacimacias** [comment]
thanks. can you please create a PR for this? so far your comments make sense to me (I have not looked at the low level details, but definitely we welcome PRs).

**Comment by kingledion** [comment]
Here is PR: https://github.com/mibes/couch-rs/pull/27

I completely removed the `ensure_index` function because it just didn't have any purpose any more. The idea of having it validate an entire list of Index against the database is pretty trivial to implement (its just a for loop through a Vec<Index> calling `insert_index` on each entry) so not sure it is worth having a specific function for it. 

The only last thing to validate is to ensure that my new IndexType enum serializes and deserializes properly.

**Comment by mibes** [comment]
Thanks for the PR. I've merged it into develop.

I'll review, but prefer to keep the `ensure_index` function for now and annotate it with `#[deprecated()]` referring to the `insert_index` function. In that way we don't break any existing code that relies on this function.

**Comment by kingledion** [comment]
That is a good point. This PR will return that function with its signature, while making it interact correctly with the new insert_index function: https://github.com/mibes/couch-rs/pull/31

**Comment by mibes** [comment]
Merged the PR and published the 0.9.1 release. Thanks for your contributions!
